name = "archives"
type = "webpack"
workers_dev = true
account_id = "e69e92ebbd12edeb09890009d14d80fa"
zone_id = "d273bbc3d952cb98a6f72f3be503eae8"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "065ed0a85b5f4fc09d2aac6799d6146b", id = "dfeee80c72d84f0cbe3b87b8957a084c" }
]

[env.staging]
name = "drive-staging"
